apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: cuebot
  POSTGRES_USER: cuebot
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_HOST: db
  POSTGRES_PORT: "5432"