apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rqd
  name: rqd
spec:
  ports:
  - name: "8444"
    port: 8444
    targetPort: 8444
  selector:
    io.kompose.service: rqd
status:
  loadBalancer: {}
